# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 169.47.93.200
  become: yes

  tasks:

- name: Call Roles
  hosts: 169.47.93.200
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
